[pytest]
pythonpath = .
addopts = -v -s
markers =
    dog: A set of tests for testing the website's API: https://dog.ceo/
    openbrewerydb: A set of tests for testing the website's API: https://www.openbrewerydb.org/
    jsonplaceholder: A set of tests for testing the website's API: https://jsonplaceholder.typicode.com/